### ISSUE TITLE
New module dialog displayed twice

### ISSUE THREAD

**Issue by festlv** [multigcs/riogui#8]
When adding a new module to config through gui, the new module dialog window is shown twice (but the module is eventually added/assigned correctly).

**Comment by multigcs** [comment]
hmm, can not reproduce :(

i fixed the layout of the 'add Module' dialog now (Labels/Comboboxes)

but do not have two windows.


BTW, i create a new brunch (dev) in riocore and merged the riogui stuff,
so in the feature, you need only the riocore repository, the riogui will be removed.
that is easier to handle :)

**Comment by multigcs** [comment]
ahh, now i see the problem, sorry, i will try to fix it

**Comment by multigcs** [comment]
fixed in  riocore dev branch
